# Preâmbulo Geral
project:
  type: book
  output-dir: docs

book:
  title: "**Curso de Análise de Dados no R**"
  subtitle: "**[Guia Prático - Parte I]**"
  date: "today"
  author:
    - name: Mário Diego Rocha Valente
      url: mario.valente@detran.pa.gov.br
      affiliation: FACTTOR/DETRAN-PA
      affiliation_url: https://www.fatoranalytics.com/
      orcid_id: 0000-0002-0559-5176
    - name: Carlos Benedito Pereira da Paixão
      url: carlos.paixao@gmail.com
      affiliation: FACTTOR
      affiliation_url: https://www.fatoranalytics.com/
      orcid_id: 0000-0003-3059-1967
    - name: Fabio Costa
      url: fabio.costa@gmail.com
      affiliation: FACTTOR
      affiliation_url: https://www.fatoranalytics.com/
      orcid_id: 0000-0003-3059-1968
  page-footer:
    left: |
      Was Written by (**VALENTE, M.D.R - 2026**).
    right: |
      FACTOR/DETRAN-PA.
  cover-image: Fator_Analytics.png
  favicon: Fator_Analytics.png
  repo-url: https://github.com/MarioDhiego
  repo-subdir: book
  repo-branch: main                      # master
  repo-actions: [edit, issue, source]
  sharing: [twitter, linkedin]
  downloads: [pdf, docx]
  page-navigation: TRUE
  reader-mode: TRUE
  sidebar:
        search: TRUE

  chapters:
    - index.qmd
    - intro.qmd
    - cap1.qmd
    - cap2.qmd
    - cap3.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
format:
  html:
    toc: true                       # Indice OU Sumário
    toc-title: SUMÁRIO              # Título do Indice
    toc-location: right             # Posição do Indice
    number-sections: TRUE           # Seção do Indice 
    theme:
      light: cosmo
      dark:  superhero
    code-fold: TRUE
    code-tools: FALSE
    code-link: TRUE
  pdf:
    documentclass: scrreport
  epub:
    cover-image: cover.png
abstract: ""






